[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.2"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Artec"]

# The title and description fields are primarly for displaying extension info in UI
title = "Browser of Models on Artec Cloud"
description="omni kit browser artec cloud models extension."

# URL of the extension source repository.
repository = ""

# Keywords for the extension
keywords = ['browser', 'asset', 'model', 'artec', 'cloud']

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

category = "services"
readme  = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/artec_cloud.png"

[dependencies]
"omni.kit.browser.core" = {version="2.1.5"}
"artec.services.browser.asset" = {version="1.0.0"}
"omni.usd" = {}
"omni.services.client" = {version="0.4.0"}
"omni.kit.window.content_browser" = { optional=true }
"omni.kit.window.filepicker" = {}

# Main python module this extension provides, it will be publicly available as "import artec.asset.browser".
[[python.module]]
name = "artec.asset.browser"

[settings]
exts."artec.asset.browser".provider = "local://"
exts."artec.asset.browser".showCategory = ""
exts."artec.asset.browser".pageSize = 25
exts."artec.asset.browser".hoverWindow = false
exts."artec.asset.browser".singleProvider = true
exts."artec.asset.browser".appSettings = "/persistent/app/artec_asset_browser"
exts."artec.asset.browser".autoScroll = true

exts."artec.asset.browser".enable = true
exts."artec.asset.browser".providerId = "ArtecCloud"
exts."artec.asset.browser".maxCountPerPage = 20
exts."artec.asset.browser".modelsUrl = "https://cloud.artec3d.com/api/omni/1.0/projects"
exts."artec.asset.browser".cloudSearchUrl = "https://cloud.artec3d.com/api/omni/1.0/projects.json"
exts."artec.asset.browser".authorizeUrl = "https://cloud.artec3d.com/api/omni/1.0/sessions"

[[test]]
dependencies = [
    "omni.kit.renderer.core",
    "omni.kit.renderer.capture",
    "artec.services.browser.asset",
    "omni.kit.browser.asset_provider.s3"
]

args = [
    "--no-window",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
]

stdoutFailPatterns.exclude = [
    "*gpu.foundation.plugin'>: Failed to load texture*", # Leak
    "*[gpu.foundation.plugin] Failed to load texture*",
    "*[gpu.foundation.plugin] Failed to read texture file*",
]
